TARGET_NAMES = Nintendo Non-Nintendo Non-Nintendo-Sony Multitap PSX-JogCon \
	Combo1 Combo2 Combo3 Combo4 Combo5 Combo6 Combo7 Combo8 Combo9 Combo10 \
	Combo11 Combo12 Combo13 Combo14 Combo15 Combo16 Combo17 Combo18 Combo19 Combo20 \
	Combo21 Combo22 Combo23 Combo24 Combo25 Combo26


# Saturn = 20%
# Saturn Multitap = 
# PSX = 
# NeGcon = 2%
# JogCon = 5%
# GunCon = 14% 
# Wii = 17%
# Jaguar = ~10%
# PCE = ~10%
# NeoGeo = 
# N64 = 
# SNES = 
# SNES Multitap = 
# 3DO = 
# SMS = 
# J-PC = 


#SNES.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DSNES_ENABLE_MULTITAP
#N64.FLAGS = -DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65
#GameCube.FLAGS = -DENABLE_REFLEX_GAMECUBE
#Wii.FLAGS = -DENABLE_REFLEX_WII
#Saturn.FLAGS = -DENABLE_REFLEX_SATURN -DSATLIB_ENABLE_MEGATAP -DSATLIB_ENABLE_SATTAP
#PSX-MiSTer.FLAGS = \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1
#PSX-PC.FLAGS = \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=0 -DENABLE_PSX_GUNCON_MOUSE -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_MOUSE -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=0
#PCEngine.FLAGS = -DENABLE_REFLEX_PCE -DPCE_ENABLE_MULTITAP
#NeoGeo.FLAGS = -DENABLE_REFLEX_NEOGEO
#Jaguar.FLAGS = -DENABLE_REFLEX_JAGUAR -DJAG_DEBOUNCE=8
#3DO.FLAGS = -DENABLE_REFLEX_3DO


# NES+SNES+VB, N64 (Scaled), GameCube, Wii
Nintendo.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DSNES_ENABLE_MULTITAP \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_WII

# Gen+Sat, PSX+GunCon+neGcon, PCE, NeoGeo, Jaguar
Non-Nintendo.FLAGS = \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1\
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO \
	-DENABLE_REFLEX_JAGUAR

# SMS+Atari+C64+JP-PC, Gen+Sat, PCE, NeoGeo, Jaguar, 3DO
Non-Nintendo-Sony.FLAGS = \
	-DENABLE_REFLEX_SMS -DENABLE_REFLEX_JPC \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO \
	-DENABLE_REFLEX_JAGUAR \
	-DENABLE_REFLEX_3DO

# NES+SNES+Tap, Gen+Saturn+Tap, PCE+Tap
Multitap.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_MULTITAP \
	-DENABLE_REFLEX_SATURN -DSATLIB_ENABLE_MEGATAP -DSATLIB_ENABLE_SATTAP \
	-DENABLE_REFLEX_PCE -DPCE_ENABLE_MULTITAP

# PSX JogCon [4 modes: Wheel (Mode+R2), Paddle (Mode+L2), Spinner (Mode+L2+R2) & Fake Spinner (Mode+R1+L1)]
PSX-JogCon.FLAGS = \
	-DENABLE_REFLEX_PSX \
	-DJOGCON_SUPPORT -DENABLE_REFLEX_PSX_JOG -DENABLE_PSX_JOGCON_OLED

# NES+SNES, Gen+Sat, PSX+Guncon+Jogcon
Combo1.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED

# NES+SNES, Gen+Sat+Tap, PSX+Guncon+neGcon
Combo2.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_SATURN -DSATLIB_ENABLE_SATTAP \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES, Gen+Sat+Tap, PSX+Jogcon+neGcon
Combo3.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_SATURN -DSATLIB_ENABLE_SATTAP \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Original), PSX+Guncon+Jogcon+neGcon, PCE
Combo4.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1 \
	-DENABLE_REFLEX_PCE

# NES+SNES, N64 (Scaled), PSX+Guncon+Jogcon+neGcon, NeoGeo, Jaguar
Combo5.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1 \
	-DENABLE_REFLEX_NEOGEO \
	-DENABLE_REFLEX_JAGUAR

# NES+SNES, Wii, PSX+Guncon+Jogcon+neGcon, NeoGeo
Combo6.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1 \
	-DENABLE_REFLEX_NEOGEO

# Gen+Sat, PSX+Guncon+Jogcon+neGcon, NeoGeo
Combo7.FLAGS = \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1 \
	-DENABLE_REFLEX_NEOGEO

# N64 (Scaled), GameCube, Wii, PCE, NeoGeo, Jaguar, 3DO
Combo8.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO \
	-DENABLE_REFLEX_JAGUAR \
	-DENABLE_REFLEX_3DO

# NES+SNES+VB, N64 (Scaled), GameCube, Wii, PSX+neGcon
Combo9.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), Wii, PSX+JogCon
Combo10.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED

# NES+SNES+VB, N64 (Scaled), Wii, PSX+GunCon+neGcon
Combo11.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), Gen+Sat, PSX
Combo12.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED

# Gen+Sat, N64 (Scaled), Wii, PSX
Combo13.FLAGS = \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED

# NES+SNES+VB, GameCube, Gen+Sat, PSX
Combo14.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED

# NES+SNES+VB, N64 (Scaled), Wii, PSX+JogCon
Combo15.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED

# NES+SNES+VB, Gen+Sat, PSX, PCE
Combo16.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_PCE

# NES+SNES+VB, N64 (Scaled), Wii, PSX+neGcon
Combo17.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, SMS+Atari+C64+JP-PC, Gen+Sat, PSX+neGcon
Combo18.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SMS -DENABLE_REFLEX_JPC \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), Gen+Sat, NeoGeo
Combo19.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_NEOGEO

# N64 (Scaled), Wii, PSX+Guncon+Jogcon+neGcon
Combo20.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED \
	-DJOGCON_SUPPORT -DENABLE_PSX_JOGCON_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), SMS+Atari+C64, Gen+Sat
Combo21.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SMS \
	-DENABLE_REFLEX_SATURN

# N64 (Scaled), Gen+Sat, PSX, PCE
Combo22.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_PCE

# NES+SNES+VB, SMS+Atari+C64, Gen+Sat, PSX
Combo23.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SMS \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED

# NES+SNES+VB, GameCube, Gen+Sat, PSX, NeoGeo
Combo24.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, SMS+Atari+C64, Gen+Sat, PSX+Guncon
Combo25.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SMS \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DGUNCON_SUPPORT -DGUNCON_FORCE_MODE=3 -DENABLE_PSX_GUNCON_OLED

# NES+SNES+VB, N64 (Scaled), SMS+Atari+C64, Gen+Sat, PSX
Combo26.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_SMS \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED


PRJ_DIR = Reflex
BUILD_DIR = build
TARGET_DIR = firmware

SRC = $(wildcard $(PRJ_DIR)/*.h $(PRJ_DIR)/*.c $(PRJ_DIR)/*.ino)
CLI_OPT = -b misteraddons:avr:reflex --config-file arduino/cli-config.yaml $(PRJ_DIR)

TARGETS = $(addsuffix .hex, $(addprefix $(TARGET_DIR)/, $(TARGET_NAMES)))

GCC_PATH := $(shell arduino-cli compile $(CLI_OPT) --show-properties | grep runtime.tools.avr-gcc.path= | sed "s/.*=//")

all: $(TARGETS) $(TARGET_DIR)/sizes.txt

$(TARGET_DIR)/%.hex: $(SRC) | $(TARGET_DIR)
	@[ "$($*.FLAGS)" ] || ( echo ">> $*.FLAGS is not set"; exit 1 )
	arduino-cli compile $(CLI_OPT) --build-property "build.extra_flags={build.usb_flags} -DREFLEX_NO_DEFAULTS $($*.FLAGS)" -e --output-dir $(BUILD_DIR)/$*
	cp $(BUILD_DIR)/$*/Reflex.ino.elf $(TARGET_DIR)/$*.elf
	cp $(BUILD_DIR)/$*/Reflex.ino.hex $(TARGET_DIR)/$*.hex

$(TARGET_DIR)/sizes.txt: $(TARGETS)
	@cd $(TARGET_DIR) && $(GCC_PATH)/bin/avr-size $(notdir $(subst .hex,.elf,$^)) 2>&1 > sizes.txt
	@echo Size Summary 
	@cat $@

$(TARGET_DIR):
	mkdir -p $@

$(TARGET_NAMES): %: $(TARGET_DIR)/%.hex

clean:
	rm -rf $(TARGET_DIR)
	rm -rf $(BUILD_DIR)

.PHONY: all clean $(TARGET_NAMES)
