TARGET_NAMES = MPGCombo1 MPGCombo2 MPGCombo3 MPGCombo4 MPGCombo5 \
	       MPGCombo6 MPGCombo7 MPGCombo8 MPGCombo9 MPGCombo10 \
	       MPGCombo11 MPGCombo12 MPGCombo13 MPGCombo14 MPGCombo15 \
	       MPGCombo16 MPGCombo17 MPGCombo18 MPGCombo19 \
	       MPGCombo23 MPGCombo24 \
	       MPGVBNSO MPGPSX1200Test


# N64 (Scaled), GameCube, PSX+neGcon
MPGCombo1.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), GameCube, SMS+Atari+C64+JP-PC, NeoGeo
MPGCombo2.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_SMS -DENABLE_REFLEX_JPC \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, N64 (Scaled), PSX+neGcon
MPGCombo3.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES, N64 (Scaled), PSX, NeoGeo
MPGCombo4.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, N64 (Scaled), GameCube, PCE, NeoGeo
MPGCombo5.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES, SMS+Atari+C64, PCE, NeoGeo, Jaguar
MPGCombo6.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_SMS \
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO \
	-DENABLE_REFLEX_JAGUAR

# SMS+Atari+C64, Gen+Sat, PSX, NeoGeo
MPGCombo7.FLAGS = \
	-DENABLE_REFLEX_SMS \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, Gen+Sat, PCE, NeoGeo
MPGCombo8.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PCE \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, N64 (Scaled), Gen+Sat
MPGCombo9.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SATURN

# N64 (Scaled), GameCube, Gen+Sat, NeoGeo
MPGCombo10.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_SATURN -DENABLE_REFLEX_NEOGEO

# Wii, PSX, 3DO
MPGCombo11.FLAGS = \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DENABLE_REFLEX_3DO

# NES+SNES, GameCube, Gen+Sat, NeoGeo
MPGCombo12.FLAGS = \
	-DENABLE_REFLEX_SNES \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_NEOGEO

# NES+SNES+VB, GameCube, PSX+neGcon
MPGCombo13.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED \
	-DNEGCON_SUPPORT -DNEGCON_FORCE_MODE=1

# NES+SNES+VB, N64 (Scaled), Wii
MPGCombo14.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII

# NES+SNES+VB, Gen+Sat, PCE
MPGCombo15.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PCE

# Gen+Sat, Wii
MPGCombo16.FLAGS = \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_WII

# NES+SNES+VB, N64 (Scaled), GameCube
MPGCombo17.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE

# NES+SNES+VB, GameCube, Wii
MPGCombo18.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_WII

# N64 (Scaled), GameCube, Wii
MPGCombo19.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_GAMECUBE \
	-DENABLE_REFLEX_WII

# N64 (Scaled), Wii, Gen+Sat
MPGCombo20.FLAGS = \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_SATURN

# Wii, Gen+Sat, PCE
MPGCombo21.FLAGS = \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_SATURN \
	-DENABLE_REFLEX_PCE

# NES+SNES+VB, Wii, Gen+Sat
MPGCombo22.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_WII \
	-DENABLE_REFLEX_SATURN

# NES+SNES+VB, N64 (Scaled), PCE
MPGCombo23.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_PCE

# NES+SNES+VB, N64 (Scaled), Gen+Sat
MPGCombo24.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY \
	-DENABLE_REFLEX_N64 -DN64_ANALOG_MAX=65 \
	-DENABLE_REFLEX_SATURN

# VB NSO (NES+SNES+VB with VB Right D-pad on Right Stick)
MPGVBNSO.FLAGS = \
	-DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DSNES_VBOY_RIGHT_DPAD_TO_RSTICK

# PSX-1200 Test (PSX Analog Init Retries for SCPH-1200)
MPGPSX1200Test.FLAGS = \
	-DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED -DPSX_1200_TEST


PRJ_DIR = ReflexMPG
BUILD_DIR = build
TARGET_DIR = firmware

SRC = $(wildcard $(PRJ_DIR)/*.h $(PRJ_DIR)/*.c $(PRJ_DIR)/*.ino)
ARDUINO_CLI = arduino-cli -b Arduino-LUFA:avr:leonardo

TARGETS = $(addsuffix .hex, $(addprefix $(TARGET_DIR)/, $(TARGET_NAMES)))

GCC_PATH := $(shell $(ARDUINO_CLI) compile $(PRJ_DIR) --show-properties | grep runtime.tools.avr-gcc.path= | sed "s/.*=//")

all: $(TARGETS) $(TARGET_DIR)/sizes.txt

$(TARGET_DIR)/%.hex: $(SRC) | $(TARGET_DIR) install-core
	@[ "$($*.FLAGS)" ] || ( echo ">> $*.FLAGS is not set"; exit 1 )
	$(ARDUINO_CLI) compile $(PRJ_DIR) --build-property "build.extra_flags={build.usb_flags} -DREFLEX_NO_DEFAULTS $($*.FLAGS)" -e --output-dir $(BUILD_DIR)/$*
	cp $(BUILD_DIR)/$*/ReflexMPG.ino.elf $(TARGET_DIR)/$*.elf
	cp $(BUILD_DIR)/$*/ReflexMPG.ino.hex $(TARGET_DIR)/$*.hex

$(TARGET_DIR)/sizes.txt: $(TARGETS)
	@cd $(TARGET_DIR) && $(GCC_PATH)/bin/avr-size $(notdir $(subst .hex,.elf,$^)) 2>&1 > sizes.txt
	@echo Size Summary 
	@cat $@

$(TARGET_DIR):
	mkdir -p $@

$(TARGET_NAMES): %: $(TARGET_DIR)/%.hex

clean:
	rm -rf $(TARGET_DIR)
	rm -rf $(BUILD_DIR)

.PHONY: all clean install-core $(TARGET_NAMES)
