name: Reflex Updater

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/updater.yml
      - reflex_updater/**
  push:
    branches: [main]
    paths:
      - .github/workflows/updater.yml
      - reflex_updater/**

concurrency:
  group: updater-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target: [ armv7-unknown-linux-musleabihf, x86_64-unknown-linux-musl]
        host: [ ubuntu-latest ]
        cross: [ true ]
        include:
          - target: x86_64-apple-darwin
            host: macos-latest
            cross: false
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            cross: false
            
    runs-on: ${{ matrix.host }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross --rev c5c9de4a8f54ed3f40c0ca9f9cc8be60c4bc4019
        if: ${{ matrix.cross }}
      - run: cross build --release --target ${{ matrix.target }}
        if: ${{ matrix.cross }}
        working-directory: reflex_updater
      - run: cargo build --release --target ${{ matrix.target }}
        if: ${{ !matrix.cross }}
        working-directory: reflex_updater
      
      #- name: Sign
      #  if: ${{ matrix.host == 'macos-latest' && env.MACOS_CERTIFICATE_PWD != '' }}
      #  run: |
      #    echo $MACOS_CERTIFICATE_PWD | base64 --decode > certificate.pwd
      #    echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
      #    version=0.22.0
      #    release="apple-codesign-${version}-x86_64-apple-darwin"
      #    tag="apple-codesign/$version"
      #    asset="${release}.tar.gz"
      #    gh release download --repo=github.com/indygreg/apple-platform-rs "$tag" --pattern "$asset"
      #    tar --extract --directory . --strip-components 1 --file "$asset" "${release}"/rcodesign
      #    ./rcodesign sign --p12-file certificate.p12 --p12-password-file certificate.pwd reflex_updater/target/${{ matrix.target }}/release/reflex_updater

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ matrix.host == 'windows-latest' }}
        with:
          name: ${{ matrix.target }}
          path: |
            reflex_updater/target/${{ matrix.target }}/release/reflex_updater.exe
            reflex_updater/target/${{ matrix.target }}/release/reflex_updater.pdb
          if-no-files-found: error
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ matrix.host != 'windows-latest' }}
        with:
          name: ${{ matrix.target }}
          path: reflex_updater/target/${{ matrix.target }}/release/reflex_updater
          if-no-files-found: error
          
  bundle:
    name: Bundle
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          path: artifacts
    
      - name: Display structure of downloaded files
        run: ls -lR
        working-directory: artifacts
        
      - name: Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: reflex_updater
          path: artifacts/
          if-no-files-found: error



